import {
  Menu,
  X,
  Rocket,
  Award,
  Home,
  Newspaper,
  User,
  Mail,
} from "lucide-react";
const fotos = {
  Cnae: [
    "/img/cnae/cnae (1).jpg",
    "/img/cnae/cnae (2).jpg",
    "/img/cnae/cnae (3).jpg",
    "/img/cnae/cnae (4).jpg",
    "/img/cnae/cnae (5).jpg",
    "/img/cnae/cnae (6).jpg",
    "/img/cnae/cnae (7).jpg",
    "/img/cnae/cnae (8).jpg",
    "/img/cnae/cnae (9).jpg",
    "/img/cnae/cnae (10).jpg",
    "/img/cnae/cnae (11).jpg",
    "/img/cnae/cnae (12).jpg",
    "/img/cnae/cnae (13).jpg",
    "/img/cnae/cnae (14).jpg",
    "/img/cnae/cnae (15).jpg",
    "/img/cnae/cnae (16).jpg",
    "/img/cnae/cnae (17).jpg",
    "/img/cnae/cnae (18).jpg",
    "/img/cnae/cnae (19).jpg",
    "/img/cnae/cnae (20).jpg",
    "/img/cnae/cnae (21).jpg",
  ],

  Cultura: [
    "/img/cultura/cultura (1).jpg",
    "/img/cultura/cultura (2).jpg",
    "/img/cultura/cultura (3).jpg",
    "/img/cultura/cultura (4).jpg",
    "/img/cultura/cultura (5).jpg",
    "/img/cultura/cultura (6).jpg",
    "/img/cultura/cultura (7).jpg",
    "/img/cultura/cultura (8).jpg",
    "/img/cultura/cultura (9).jpg",
    "/img/cultura/cultura (10).jpg",
    "/img/cultura/cultura (11).jpg",
    "/img/cultura/cultura (12).jpg",
    "/img/cultura/cultura (13).jpg",
    "/img/cultura/cultura (14).jpg",
    "/img/cultura/cultura (15).jpg",
    "/img/cultura/cultura (16).jpg",
    "/img/cultura/cultura (17).jpg",
    "/img/cultura/cultura (18).jpg",
    "/img/cultura/cultura (19).jpg",
    "/img/cultura/cultura (20).jpg",
    "/img/cultura/cultura (21).jpg",
  ],
  Evento: [
    "/img/evento/evento (1).jpg",
    "/img/evento/evento (2).jpg",
    "/img/evento/evento (3).jpg",
    "/img/evento/evento (4).jpg",
    "/img/evento/evento (5).jpg",
    "/img/evento/evento (6).jpg",
    "/img/evento/evento (7).jpg",
    "/img/evento/evento (8).jpg",
    "/img/evento/evento (9).jpg",
    "/img/evento/evento (10).jpg",
    "/img/evento/evento (11).jpg",
    "/img/evento/evento (12).jpg",
    "/img/evento/evento (13).jpg",
    "/img/evento/evento (14).jpg",
    "/img/evento/evento (15).jpg",
    "/img/evento/evento (16).jpg",
    "/img/evento/evento (17).jpg",
    "/img/evento/evento (18).jpg",
    "/img/evento/evento (19).jpg",
    "/img/evento/evento (20).jpg",
    "/img/evento/evento (21).jpg",
  ],
  Contenido: [
    "/img/evento/evento (1).jpg",
    "/img/evento/evento (2).jpg",
    "/img/evento/evento (3).jpg",
    "/img/evento/evento (4).jpg",
    "/img/evento/evento (5).jpg",
    "/img/evento/evento (6).jpg",
    "/img/evento/evento (7).jpg",
    "/img/evento/evento (8).jpg",
    "/img/evento/evento (9).jpg",
    "/img/evento/evento (10).jpg",
    "/img/evento/evento (11).jpg",
    "/img/evento/evento (12).jpg",
    "/img/evento/evento (13).jpg",
    "/img/evento/evento (14).jpg",
    "/img/evento/evento (15).jpg",
    "/img/evento/evento (16).jpg",
    "/img/evento/evento (17).jpg",
    "/img/evento/evento (18).jpg",
    "/img/evento/evento (19).jpg",
    "/img/evento/evento (20).jpg",
    "/img/evento/evento (21).jpg",
  ],
  Blog: [
    "/img/evento/evento (1).jpg",
    "/img/evento/evento (2).jpg",
    "/img/evento/evento (3).jpg",
    "/img/evento/evento (4).jpg",
    "/img/evento/evento (5).jpg",
    "/img/evento/evento (6).jpg",
    "/img/evento/evento (7).jpg",
    "/img/evento/evento (8).jpg",
    "/img/evento/evento (9).jpg",
    "/img/evento/evento (10).jpg",
    "/img/evento/evento (11).jpg",
    "/img/evento/evento (12).jpg",
    "/img/evento/evento (13).jpg",
    "/img/evento/evento (14).jpg",
    "/img/evento/evento (15).jpg",
    "/img/evento/evento (16).jpg",
    "/img/evento/evento (17).jpg",
    "/img/evento/evento (18).jpg",
    "/img/evento/evento (19).jpg",
    "/img/evento/evento (20).jpg",
    "/img/evento/evento (21).jpg",
  ],
  Acerca: [
    "/img/evento/evento (1).jpg",
    "/img/evento/evento (2).jpg",
    "/img/evento/evento (3).jpg",
    "/img/evento/evento (4).jpg",
    "/img/evento/evento (5).jpg",
    "/img/evento/evento (6).jpg",
    "/img/evento/evento (7).jpg",
    "/img/evento/evento (8).jpg",
    "/img/evento/evento (9).jpg",
    "/img/evento/evento (10).jpg",
    "/img/evento/evento (11).jpg",
    "/img/evento/evento (12).jpg",
    "/img/evento/evento (13).jpg",
    "/img/evento/evento (14).jpg",
    "/img/evento/evento (15).jpg",
    "/img/evento/evento (16).jpg",
    "/img/evento/evento (17).jpg",
    "/img/evento/evento (18).jpg",
    "/img/evento/evento (19).jpg",
    "/img/evento/evento (20).jpg",
    "/img/evento/evento (21).jpg",
  ],
};
const texto = [
  {
    titulo: "Reseña Histórica",
    info: "La Escuela Básica Nacional Bolivariana “Creación Robert Serra” fue inaugurada el 1 de octubre de 2018 por el profesor Aristóbulo Istúriz Almeida, ministro del poder popular para la educación. La escuela se construyó para responder a las necesidades de la población escolar del complejo urbanístico Ciudad Socialista Los Aviadores, el cual se comenzó a edificar en 2013 como parte de la Gran Misión Vivienda Venezuela para resolver el déficit habitacional del país. El urbanismo fue un proyecto en convenio con la República de Bielorrusia y se entregó en dos etapas entre 2015 y 2016. La escuela fue nombrada en honor a Robert Serra Aguirre, un joven líder social y diputado. La institución inició con 599 estudiantes y un equipo de personal comprometido con la formación de ciudadanos a través de valores éticos, morales, sociales y ambientales.",
  },
  {
    titulo: "Resumen",
    info: "La Escuela Básica Nacional Bolivariana “Creación Robert Serra” es una institución pública oficial en el estado Aragua. Este documento establece los acuerdos de paz, convivencia escolar y comunitaria para el año escolar 2024-2025. Incluye la reseña histórica de la escuela, sus datos de identificación, sus principios fundamentales, objetivos, filosofía institucional, visión y misión, así como bases legales y perfiles del personal directivo, docente, administrativo, obrero y de la comunidad educativa. El documento busca la formación de ciudadanos con un sentido crítico y ético, promoviendo el diálogo, la paz y la convivencia en toda la comunidad educativa.",
  },
  {
    titulo: "Misión",
    info: "Crear estrategias motivadoras e innovadoras que permitan la construcción colectiva, el intercambio de saberes y la participación comunitaria. Garantiza el cumplimiento de los fines educativos del estado para la formación ciudadana, rompiendo con la planificación clásica para construir una nueva escuela que responda a las necesidades pedagógicas y de formación de la comunidad educativa.",
  },
  {
    titulo: "Visión",
    info: "La institución se proyecta para formar a los estudiantes para la vida. Busca una enseñanza altamente calificada, que es un proceso abierto y permite que los niños y niñas aprendan ejercitando sus capacidades. Pretende desmontar la creencia de que solo se aprende con pizarra y marcador, ofreciendo oportunidades que involucren la mente, las manos y el corazón, superando la separación entre el trabajo manual e intelectual.",
  },
  {
    titulo: "Objetivo General",
    info: "Establecer las normativas de los Acuerdos de paz, convivencia escolar y comunitaria, basándose en el respeto, la tolerancia y la unión para generar un clima de armonía.",
  },
  {
    titulo: "Objetivos Específicos",
    info: [
      "Promover el diálogo y la mediación.",
      "Reflejar estrategias de convivencia en los proyectos institucionales.",
      "Orientar a padres, madres y representantes sobre sus deberes y derechos para garantizar la convivencia.",
    ],
  },
  {
    titulo: "Principios Fundamentales",
    info: "La filosofía institucional busca formar ciudadanos con sentido crítico, ético e investigativo, basados en valores humanistas y socialistas de la doctrina de Simón Bolívar, contribuyendo a la mejora de la comunidad para alcanzar la felicidad social. También busca formar individuos conscientes de sí mismos, que desarrollen plenamente sus dimensiones psicológica, biológica, social y afectiva. La institución promueve valores humanos, autonomía, crítica responsable, solidaridad y convivencia, y un compromiso de servicio y transformación social.",
  },
];
export const navItems = [
  { name: "Inicio", href: "/", isLink: true, icon: <Home size={18} /> },
  {
    name: "Blog",
    href: "#Blog",
    contenido:
      "Descubre nuestras últimas publicaciones, artículos de interés y noticias relevantes sobre el mundo de la educación y la tecnología.",
    fotos: fotos.Contenido,

    isLink: false,
    icon: <Newspaper size={18} />,
  },
  {
    name: "Acerca de",
    href: "#Acerca de",
    contenido:
      "Conoce más sobre nuestra misión, visión y el equipo que hace posible este proyecto educativo.",
    texto: texto,
    isLink: false,
    icon: <User size={18} />,
  },
  {
    name: "Eventos",
    href: "#Eventos",
    contenido:
      "Mantente al día con los próximos talleres, seminarios web y eventos especiales que hemos preparado para ti.",
    fotos: fotos.Eventos,

    isLink: false,
    icon: <Award size={18} />,
  },
  {
    name: "Contacto",
    href: "#Contacto",
    contenido:
      "Ponte en contacto con nosotros para cualquier consulta, sugerencia o colaboración. ¡Nos encantaría saber de ti!",
    fotos: fotos.Contacto,
    isLink: false,
    icon: <Mail size={18} />,
  },
];
