export const personalFormConfig = [
  { name: "id_persona", label: "Persona", type: "select", required: true },
  {
    name: "cargo",
    label: "Cargo",
    type: "select",
    required: true,
    options: [
      "DOCENTE_I",
      "DOCENTE_II",
      "DOCENTE_III",
      "DOCENTE_IV",
      "DOCENTE_V",
      "DOCENTE_VI",
      "BACHILLER_DOCENTE",
      "DOCENTE_TSU",
      "DOCENTE_COORDINADOR",
      "DOCENTE_SUBDIRECTOR",
      "DOCENTE_DIRECTOR",
      "DOCENTE_SUPERVISOR",
      "PROFESOR_INSTRUCTOR",
      "PROFESOR_ASISTENTE",
      "PROFESOR_AGREGADO",
      "PROFESOR_ASOCIADO",
      "PROFESOR_TITULAR",
      "MADRE_COCINERA",
      "COORDINADOR_CNAE_MUNICIPAL",
      "VOCERO_CNAE_INSTITUCIONAL",
      "TUTOR_CBIT",
      "ANALISTA_ADMINISTRATIVO",
      "ASISTENTE_ADMINISTRATIVO",
      "PROFESIONAL_NO_DOCENTE",
      "JEFE_DE_UNIDAD",
      "ALTO_NIVEL_O_CONFIANZA",
      "OBRERO_I",
      "OBRERO_II",
      "OBRERO_III",
      "PERSONAL_DE_VIGILANCIA",
    ],
  },
  {
    name: "funcion",
    label: "Función",
    type: "select",
    required: true,
    options: ["Docente", "Administrativo", "Obrero", "CBIT", "CNAE", "UPE"],
  },
  {
    name: "fecha_contratacion",
    label: "Fecha contratación",
    type: "date",
    required: true,
  },
  { name: "codigo_rac", label: "Código RAC", type: "text" },
  { name: "nivel_academico", label: "Nivel académico", type: "text" },
  { name: "anios_servicio", label: "Años de servicio", type: "number" },
  {
    name: "horas_trabajo",
    label: "Horas trabajo (HH:MM o HH:MM:SS)",
    type: "time",
  },
  { name: "situacion_trabajador", label: "Situación trabajador", type: "text" },
  { name: "observacion", label: "Observación", type: "textarea" },
  { name: "rif", label: "RIF", type: "text" },
  { name: "estado_civil", label: "Estado civil", type: "text" },
  { name: "etnia_religion", label: "Etnia / Religión", type: "text" },
  { name: "cantidad_hijas", label: "Cantidad hijas", type: "number" },
  {
    name: "cantidad_hijos_varones",
    label: "Cantidad hijos varones",
    type: "number",
  },
];
